services:
  shopiapi:
    image: shopiapi
    build:
      context: .
      dockerfile: ShopiAPI/Dockerfile

  shopiapi-1:
    image: shopiapi-1
    build:
      context: .
      dockerfile: src/ShopiAPI/Dockerfile
